# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import analytics_pb2 as analytics__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub:
    """Contrato gRPC unificado del microservicio de Analítica (Python/FastAPI).
    Único consumidor de negocio: api-gateway. analytics-service además actúa como
    cliente gRPC de ReproduccionService (checkpoints.proto) para sincronizar métricas;
    eso no cambia con este contrato, que es solo el lado servidor de analytics-service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideoMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/GetVideoMetrics',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetCourseMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/GetCourseMetrics',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetTeacherStats = channel.unary_unary(
                '/analytics.AnalyticsService/GetTeacherStats',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetStudentProgress = channel.unary_unary(
                '/analytics.AnalyticsService/GetStudentProgress',
                request_serializer=analytics__pb2.StudentCourseRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.SyncVideoMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/SyncVideoMetrics',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetTopVideos = channel.unary_unary(
                '/analytics.AnalyticsService/GetTopVideos',
                request_serializer=analytics__pb2.LimitRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetSystemStats = channel.unary_unary(
                '/analytics.AnalyticsService/GetSystemStats',
                request_serializer=analytics__pb2.Empty.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetTeacherPerformance = channel.unary_unary(
                '/analytics.AnalyticsService/GetTeacherPerformance',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetCourseProgress = channel.unary_unary(
                '/analytics.AnalyticsService/GetCourseProgress',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetVideoEngagement = channel.unary_unary(
                '/analytics.AnalyticsService/GetVideoEngagement',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer:
    """Contrato gRPC unificado del microservicio de Analítica (Python/FastAPI).
    Único consumidor de negocio: api-gateway. analytics-service además actúa como
    cliente gRPC de ReproduccionService (checkpoints.proto) para sincronizar métricas;
    eso no cambia con este contrato, que es solo el lado servidor de analytics-service.
    """

    def GetVideoMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourseMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeacherStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncVideoMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopVideos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeacherPerformance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourseProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideoEngagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideoMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoMetrics,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetCourseMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseMetrics,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetTeacherStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeacherStats,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetStudentProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentProgress,
                    request_deserializer=analytics__pb2.StudentCourseRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'SyncVideoMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncVideoMetrics,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetTopVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopVideos,
                    request_deserializer=analytics__pb2.LimitRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetSystemStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStats,
                    request_deserializer=analytics__pb2.Empty.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetTeacherPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeacherPerformance,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetCourseProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseProgress,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetVideoEngagement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoEngagement,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService:
    """Contrato gRPC unificado del microservicio de Analítica (Python/FastAPI).
    Único consumidor de negocio: api-gateway. analytics-service además actúa como
    cliente gRPC de ReproduccionService (checkpoints.proto) para sincronizar métricas;
    eso no cambia con este contrato, que es solo el lado servidor de analytics-service.
    """

    @staticmethod
    def GetVideoMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetVideoMetrics',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCourseMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetCourseMetrics',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeacherStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTeacherStats',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudentProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetStudentProgress',
            analytics__pb2.StudentCourseRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncVideoMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/SyncVideoMetrics',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTopVideos',
            analytics__pb2.LimitRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetSystemStats',
            analytics__pb2.Empty.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeacherPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTeacherPerformance',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCourseProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetCourseProgress',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVideoEngagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetVideoEngagement',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
