# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.grpc import analytics_pb2 as analytics__pb2


class AnalyticsServiceStub(object):
    """Contrato gRPC unificado del microservicio de Analítica (Python/FastAPI).
    Único consumidor de negocio: api-gateway. analytics-service además actúa como
    cliente gRPC de ReproduccionService (checkpoints.proto) para sincronizar métricas;
    eso no cambia con este contrato, que es solo el lado servidor de analytics-service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideoMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/GetVideoMetrics',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetCourseMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/GetCourseMetrics',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetTeacherStats = channel.unary_unary(
                '/analytics.AnalyticsService/GetTeacherStats',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetStudentProgress = channel.unary_unary(
                '/analytics.AnalyticsService/GetStudentProgress',
                request_serializer=analytics__pb2.StudentCourseRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.SyncVideoMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/SyncVideoMetrics',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetTopVideos = channel.unary_unary(
                '/analytics.AnalyticsService/GetTopVideos',
                request_serializer=analytics__pb2.LimitRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetSystemStats = channel.unary_unary(
                '/analytics.AnalyticsService/GetSystemStats',
                request_serializer=analytics__pb2.Empty.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetTeacherPerformance = channel.unary_unary(
                '/analytics.AnalyticsService/GetTeacherPerformance',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetCourseProgress = channel.unary_unary(
                '/analytics.AnalyticsService/GetCourseProgress',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetVideoEngagement = channel.unary_unary(
                '/analytics.AnalyticsService/GetVideoEngagement',
                request_serializer=analytics__pb2.IdRequest.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetWeeklyTopVideos = channel.unary_unary(
                '/analytics.AnalyticsService/GetWeeklyTopVideos',
                request_serializer=analytics__pb2.LimitRequest.SerializeToString,
                response_deserializer=analytics__pb2.CachedResponse.FromString,
                )
        self.GetTopRatedVideos = channel.unary_unary(
                '/analytics.AnalyticsService/GetTopRatedVideos',
                request_serializer=analytics__pb2.LimitRequest.SerializeToString,
                response_deserializer=analytics__pb2.CachedResponse.FromString,
                )
        self.GetTrendingCourses = channel.unary_unary(
                '/analytics.AnalyticsService/GetTrendingCourses',
                request_serializer=analytics__pb2.LimitRequest.SerializeToString,
                response_deserializer=analytics__pb2.CachedResponse.FromString,
                )
        self.SnapshotWeeklyViews = channel.unary_unary(
                '/analytics.AnalyticsService/SnapshotWeeklyViews',
                request_serializer=analytics__pb2.Empty.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )
        self.GetCacheStats = channel.unary_unary(
                '/analytics.AnalyticsService/GetCacheStats',
                request_serializer=analytics__pb2.Empty.SerializeToString,
                response_deserializer=analytics__pb2.JsonResponse.FromString,
                )


class AnalyticsServiceServicer(object):
    """Contrato gRPC unificado del microservicio de Analítica (Python/FastAPI).
    Único consumidor de negocio: api-gateway. analytics-service además actúa como
    cliente gRPC de ReproduccionService (checkpoints.proto) para sincronizar métricas;
    eso no cambia con este contrato, que es solo el lado servidor de analytics-service.
    """

    def GetVideoMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourseMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeacherStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncVideoMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopVideos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeacherPerformance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourseProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideoEngagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeeklyTopVideos(self, request, context):
        """── Tendencias con caché en Redis (Proyecto Fase 1) ──────────────────────
        Son las consultas más repetidas de la plataforma: todos los estudiantes ven
        el mismo ranking, así que se sirven desde Redis con TTL en vez de recalcular
        el agregado en MySQL por cada petición.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopRatedVideos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrendingCourses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotWeeklyViews(self, request, context):
        """Operativas de la caché: la primera dispara la instantánea semanal e invalida
        los rankings; la segunda expone el estado de Redis para poder verificarlo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCacheStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideoMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoMetrics,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetCourseMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseMetrics,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetTeacherStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeacherStats,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetStudentProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentProgress,
                    request_deserializer=analytics__pb2.StudentCourseRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'SyncVideoMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncVideoMetrics,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetTopVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopVideos,
                    request_deserializer=analytics__pb2.LimitRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetSystemStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStats,
                    request_deserializer=analytics__pb2.Empty.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetTeacherPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeacherPerformance,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetCourseProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseProgress,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetVideoEngagement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoEngagement,
                    request_deserializer=analytics__pb2.IdRequest.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetWeeklyTopVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeeklyTopVideos,
                    request_deserializer=analytics__pb2.LimitRequest.FromString,
                    response_serializer=analytics__pb2.CachedResponse.SerializeToString,
            ),
            'GetTopRatedVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopRatedVideos,
                    request_deserializer=analytics__pb2.LimitRequest.FromString,
                    response_serializer=analytics__pb2.CachedResponse.SerializeToString,
            ),
            'GetTrendingCourses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrendingCourses,
                    request_deserializer=analytics__pb2.LimitRequest.FromString,
                    response_serializer=analytics__pb2.CachedResponse.SerializeToString,
            ),
            'SnapshotWeeklyViews': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotWeeklyViews,
                    request_deserializer=analytics__pb2.Empty.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
            'GetCacheStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheStats,
                    request_deserializer=analytics__pb2.Empty.FromString,
                    response_serializer=analytics__pb2.JsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Contrato gRPC unificado del microservicio de Analítica (Python/FastAPI).
    Único consumidor de negocio: api-gateway. analytics-service además actúa como
    cliente gRPC de ReproduccionService (checkpoints.proto) para sincronizar métricas;
    eso no cambia con este contrato, que es solo el lado servidor de analytics-service.
    """

    @staticmethod
    def GetVideoMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetVideoMetrics',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCourseMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetCourseMetrics',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTeacherStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetTeacherStats',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudentProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetStudentProgress',
            analytics__pb2.StudentCourseRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncVideoMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/SyncVideoMetrics',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetTopVideos',
            analytics__pb2.LimitRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetSystemStats',
            analytics__pb2.Empty.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTeacherPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetTeacherPerformance',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCourseProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetCourseProgress',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVideoEngagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetVideoEngagement',
            analytics__pb2.IdRequest.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWeeklyTopVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetWeeklyTopVideos',
            analytics__pb2.LimitRequest.SerializeToString,
            analytics__pb2.CachedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopRatedVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetTopRatedVideos',
            analytics__pb2.LimitRequest.SerializeToString,
            analytics__pb2.CachedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTrendingCourses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetTrendingCourses',
            analytics__pb2.LimitRequest.SerializeToString,
            analytics__pb2.CachedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SnapshotWeeklyViews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/SnapshotWeeklyViews',
            analytics__pb2.Empty.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCacheStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analytics.AnalyticsService/GetCacheStats',
            analytics__pb2.Empty.SerializeToString,
            analytics__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
