# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\"\x07\n\x05\x45mpty\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"=\n\x14StudentCourseRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x11\n\tcourse_id\x18\x02 \x01(\x05\"\x1d\n\x0cLimitRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"\x1c\n\x0cJsonResponse\x12\x0c\n\x04json\x18\x01 \x01(\t2\xbc\x05\n\x10\x41nalyticsService\x12@\n\x0fGetVideoMetrics\x12\x14.analytics.IdRequest\x1a\x17.analytics.JsonResponse\x12\x41\n\x10GetCourseMetrics\x12\x14.analytics.IdRequest\x1a\x17.analytics.JsonResponse\x12@\n\x0fGetTeacherStats\x12\x14.analytics.IdRequest\x1a\x17.analytics.JsonResponse\x12N\n\x12GetStudentProgress\x12\x1f.analytics.StudentCourseRequest\x1a\x17.analytics.JsonResponse\x12\x41\n\x10SyncVideoMetrics\x12\x14.analytics.IdRequest\x1a\x17.analytics.JsonResponse\x12@\n\x0cGetTopVideos\x12\x17.analytics.LimitRequest\x1a\x17.analytics.JsonResponse\x12;\n\x0eGetSystemStats\x12\x10.analytics.Empty\x1a\x17.analytics.JsonResponse\x12\x46\n\x15GetTeacherPerformance\x12\x14.analytics.IdRequest\x1a\x17.analytics.JsonResponse\x12\x42\n\x11GetCourseProgress\x12\x14.analytics.IdRequest\x1a\x17.analytics.JsonResponse\x12\x43\n\x12GetVideoEngagement\x12\x14.analytics.IdRequest\x1a\x17.analytics.JsonResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_IDREQUEST']._serialized_start=39
  _globals['_IDREQUEST']._serialized_end=62
  _globals['_STUDENTCOURSEREQUEST']._serialized_start=64
  _globals['_STUDENTCOURSEREQUEST']._serialized_end=125
  _globals['_LIMITREQUEST']._serialized_start=127
  _globals['_LIMITREQUEST']._serialized_end=156
  _globals['_JSONRESPONSE']._serialized_start=158
  _globals['_JSONRESPONSE']._serialized_end=186
  _globals['_ANALYTICSSERVICE']._serialized_start=189
  _globals['_ANALYTICSSERVICE']._serialized_end=889
# @@protoc_insertion_point(module_scope)
