# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import checkpoints_pb2 as checkpoints__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in checkpoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReproduccionServiceStub:
    """Contrato gRPC unificado del microservicio de Reproducción (Go). Dos consumidores:
    api-gateway (todas las RPCs, ya que /api/videos, /api/checkpoints y /api/ratings
    dejaron de ser REST) y analytics-service (GetVideoStats/GetUserProgress, para
    sincronizar sus métricas propias en MySQL).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCheckpoint = channel.unary_unary(
                '/reproduccion.ReproduccionService/GetCheckpoint',
                request_serializer=checkpoints__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.CheckpointResponse.FromString,
                _registered_method=True)
        self.SaveCheckpoint = channel.unary_unary(
                '/reproduccion.ReproduccionService/SaveCheckpoint',
                request_serializer=checkpoints__pb2.SaveCheckpointRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.CheckpointResponse.FromString,
                _registered_method=True)
        self.GetVideoStats = channel.unary_unary(
                '/reproduccion.ReproduccionService/GetVideoStats',
                request_serializer=checkpoints__pb2.VideoStatsRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.VideoStatsResponse.FromString,
                _registered_method=True)
        self.SaveRating = channel.unary_unary(
                '/reproduccion.ReproduccionService/SaveRating',
                request_serializer=checkpoints__pb2.SaveRatingRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.RatingStatsResponse.FromString,
                _registered_method=True)
        self.GetRatingStats = channel.unary_unary(
                '/reproduccion.ReproduccionService/GetRatingStats',
                request_serializer=checkpoints__pb2.VideoStatsRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.RatingStatsResponse.FromString,
                _registered_method=True)
        self.GetUserProgress = channel.unary_unary(
                '/reproduccion.ReproduccionService/GetUserProgress',
                request_serializer=checkpoints__pb2.UserProgressRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.UserProgressResponse.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/reproduccion.ReproduccionService/StartSession',
                request_serializer=checkpoints__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.RecordEvent = channel.unary_unary(
                '/reproduccion.ReproduccionService/RecordEvent',
                request_serializer=checkpoints__pb2.RecordEventRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.Ack.FromString,
                _registered_method=True)


class ReproduccionServiceServicer:
    """Contrato gRPC unificado del microservicio de Reproducción (Go). Dos consumidores:
    api-gateway (todas las RPCs, ya que /api/videos, /api/checkpoints y /api/ratings
    dejaron de ser REST) y analytics-service (GetVideoStats/GetUserProgress, para
    sincronizar sus métricas propias en MySQL).
    """

    def GetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideoStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRatingStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReproduccionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=checkpoints__pb2.CheckpointRequest.FromString,
                    response_serializer=checkpoints__pb2.CheckpointResponse.SerializeToString,
            ),
            'SaveCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCheckpoint,
                    request_deserializer=checkpoints__pb2.SaveCheckpointRequest.FromString,
                    response_serializer=checkpoints__pb2.CheckpointResponse.SerializeToString,
            ),
            'GetVideoStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoStats,
                    request_deserializer=checkpoints__pb2.VideoStatsRequest.FromString,
                    response_serializer=checkpoints__pb2.VideoStatsResponse.SerializeToString,
            ),
            'SaveRating': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveRating,
                    request_deserializer=checkpoints__pb2.SaveRatingRequest.FromString,
                    response_serializer=checkpoints__pb2.RatingStatsResponse.SerializeToString,
            ),
            'GetRatingStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRatingStats,
                    request_deserializer=checkpoints__pb2.VideoStatsRequest.FromString,
                    response_serializer=checkpoints__pb2.RatingStatsResponse.SerializeToString,
            ),
            'GetUserProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProgress,
                    request_deserializer=checkpoints__pb2.UserProgressRequest.FromString,
                    response_serializer=checkpoints__pb2.UserProgressResponse.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=checkpoints__pb2.StartSessionRequest.FromString,
                    response_serializer=checkpoints__pb2.StartSessionResponse.SerializeToString,
            ),
            'RecordEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordEvent,
                    request_deserializer=checkpoints__pb2.RecordEventRequest.FromString,
                    response_serializer=checkpoints__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reproduccion.ReproduccionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reproduccion.ReproduccionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReproduccionService:
    """Contrato gRPC unificado del microservicio de Reproducción (Go). Dos consumidores:
    api-gateway (todas las RPCs, ya que /api/videos, /api/checkpoints y /api/ratings
    dejaron de ser REST) y analytics-service (GetVideoStats/GetUserProgress, para
    sincronizar sus métricas propias en MySQL).
    """

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/GetCheckpoint',
            checkpoints__pb2.CheckpointRequest.SerializeToString,
            checkpoints__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/SaveCheckpoint',
            checkpoints__pb2.SaveCheckpointRequest.SerializeToString,
            checkpoints__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVideoStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/GetVideoStats',
            checkpoints__pb2.VideoStatsRequest.SerializeToString,
            checkpoints__pb2.VideoStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/SaveRating',
            checkpoints__pb2.SaveRatingRequest.SerializeToString,
            checkpoints__pb2.RatingStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRatingStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/GetRatingStats',
            checkpoints__pb2.VideoStatsRequest.SerializeToString,
            checkpoints__pb2.RatingStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/GetUserProgress',
            checkpoints__pb2.UserProgressRequest.SerializeToString,
            checkpoints__pb2.UserProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/StartSession',
            checkpoints__pb2.StartSessionRequest.SerializeToString,
            checkpoints__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/RecordEvent',
            checkpoints__pb2.RecordEventRequest.SerializeToString,
            checkpoints__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
