# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.grpc import notifications_pb2 as notifications__pb2


class NotificationServiceStub(object):
    """Contrato gRPC del microservicio de Notificaciones (Python).

    A diferencia del resto, sus consumidores no son el api-gateway sino otros
    microservicios: auth-service avisa cuando alguien se registra y catalog-service
    cuando se publica una grabación. El gateway solo consulta la bitácora, que es
    lo único que necesita el panel administrativo.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendWelcomeEmail = channel.unary_unary(
                '/notifications.NotificationService/SendWelcomeEmail',
                request_serializer=notifications__pb2.WelcomeRequest.SerializeToString,
                response_deserializer=notifications__pb2.SendResponse.FromString,
                )
        self.SendNewRecordingAlert = channel.unary_unary(
                '/notifications.NotificationService/SendNewRecordingAlert',
                request_serializer=notifications__pb2.NewRecordingRequest.SerializeToString,
                response_deserializer=notifications__pb2.SendResponse.FromString,
                )
        self.SendSystemNotice = channel.unary_unary(
                '/notifications.NotificationService/SendSystemNotice',
                request_serializer=notifications__pb2.SystemNoticeRequest.SerializeToString,
                response_deserializer=notifications__pb2.SendResponse.FromString,
                )
        self.ListNotifications = channel.unary_unary(
                '/notifications.NotificationService/ListNotifications',
                request_serializer=notifications__pb2.ListRequest.SerializeToString,
                response_deserializer=notifications__pb2.JsonResponse.FromString,
                )
        self.GetNotificationStats = channel.unary_unary(
                '/notifications.NotificationService/GetNotificationStats',
                request_serializer=notifications__pb2.Empty.SerializeToString,
                response_deserializer=notifications__pb2.JsonResponse.FromString,
                )


class NotificationServiceServicer(object):
    """Contrato gRPC del microservicio de Notificaciones (Python).

    A diferencia del resto, sus consumidores no son el api-gateway sino otros
    microservicios: auth-service avisa cuando alguien se registra y catalog-service
    cuando se publica una grabación. El gateway solo consulta la bitácora, que es
    lo único que necesita el panel administrativo.
    """

    def SendWelcomeEmail(self, request, context):
        """Confirmación de registro a la cuenta institucional.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNewRecordingAlert(self, request, context):
        """Aviso de nueva clase grabada a los estudiantes inscritos en el curso.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSystemNotice(self, request, context):
        """Aviso genérico del sistema (mantenimiento, cambios de credenciales…).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotifications(self, request, context):
        """Bitácora de envíos, para evidenciar en el panel qué se mandó y qué falló.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNotificationStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendWelcomeEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWelcomeEmail,
                    request_deserializer=notifications__pb2.WelcomeRequest.FromString,
                    response_serializer=notifications__pb2.SendResponse.SerializeToString,
            ),
            'SendNewRecordingAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNewRecordingAlert,
                    request_deserializer=notifications__pb2.NewRecordingRequest.FromString,
                    response_serializer=notifications__pb2.SendResponse.SerializeToString,
            ),
            'SendSystemNotice': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSystemNotice,
                    request_deserializer=notifications__pb2.SystemNoticeRequest.FromString,
                    response_serializer=notifications__pb2.SendResponse.SerializeToString,
            ),
            'ListNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotifications,
                    request_deserializer=notifications__pb2.ListRequest.FromString,
                    response_serializer=notifications__pb2.JsonResponse.SerializeToString,
            ),
            'GetNotificationStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotificationStats,
                    request_deserializer=notifications__pb2.Empty.FromString,
                    response_serializer=notifications__pb2.JsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notifications.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Contrato gRPC del microservicio de Notificaciones (Python).

    A diferencia del resto, sus consumidores no son el api-gateway sino otros
    microservicios: auth-service avisa cuando alguien se registra y catalog-service
    cuando se publica una grabación. El gateway solo consulta la bitácora, que es
    lo único que necesita el panel administrativo.
    """

    @staticmethod
    def SendWelcomeEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notifications.NotificationService/SendWelcomeEmail',
            notifications__pb2.WelcomeRequest.SerializeToString,
            notifications__pb2.SendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendNewRecordingAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notifications.NotificationService/SendNewRecordingAlert',
            notifications__pb2.NewRecordingRequest.SerializeToString,
            notifications__pb2.SendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendSystemNotice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notifications.NotificationService/SendSystemNotice',
            notifications__pb2.SystemNoticeRequest.SerializeToString,
            notifications__pb2.SendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notifications.NotificationService/ListNotifications',
            notifications__pb2.ListRequest.SerializeToString,
            notifications__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNotificationStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notifications.NotificationService/GetNotificationStats',
            notifications__pb2.Empty.SerializeToString,
            notifications__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
