# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\rnotifications\"\x07\n\x05\x45mpty\"\x1c\n\x0cJsonResponse\x12\x0c\n\x04json\x18\x01 \x01(\t\"H\n\x0cSendResponse\x12\x0e\n\x06queued\x18\x01 \x01(\x08\x12\x17\n\x0fnotification_id\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"@\n\x0eWelcomeRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"\x8e\x01\n\x13NewRecordingRequest\x12\x14\n\x0crecording_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x63ourse_name\x18\x03 \x01(\t\x12\x13\n\x0b\x63ourse_code\x18\x04 \x01(\t\x12\x14\n\x0cteacher_name\x18\x05 \x01(\t\x12\x12\n\nrecipients\x18\x06 \x03(\t\"H\n\x13SystemNoticeRequest\x12\x12\n\nrecipients\x18\x01 \x03(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\",\n\x0bListRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t2\xad\x03\n\x13NotificationService\x12N\n\x10SendWelcomeEmail\x12\x1d.notifications.WelcomeRequest\x1a\x1b.notifications.SendResponse\x12X\n\x15SendNewRecordingAlert\x12\".notifications.NewRecordingRequest\x1a\x1b.notifications.SendResponse\x12S\n\x10SendSystemNotice\x12\".notifications.SystemNoticeRequest\x1a\x1b.notifications.SendResponse\x12L\n\x11ListNotifications\x12\x1a.notifications.ListRequest\x1a\x1b.notifications.JsonResponse\x12I\n\x14GetNotificationStats\x12\x14.notifications.Empty\x1a\x1b.notifications.JsonResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_JSONRESPONSE']._serialized_start=47
  _globals['_JSONRESPONSE']._serialized_end=75
  _globals['_SENDRESPONSE']._serialized_start=77
  _globals['_SENDRESPONSE']._serialized_end=149
  _globals['_WELCOMEREQUEST']._serialized_start=151
  _globals['_WELCOMEREQUEST']._serialized_end=215
  _globals['_NEWRECORDINGREQUEST']._serialized_start=218
  _globals['_NEWRECORDINGREQUEST']._serialized_end=360
  _globals['_SYSTEMNOTICEREQUEST']._serialized_start=362
  _globals['_SYSTEMNOTICEREQUEST']._serialized_end=434
  _globals['_LISTREQUEST']._serialized_start=436
  _globals['_LISTREQUEST']._serialized_end=480
  _globals['_NOTIFICATIONSERVICE']._serialized_start=483
  _globals['_NOTIFICATIONSERVICE']._serialized_end=912
# @@protoc_insertion_point(module_scope)
